on: workflow_dispatch

name: ReactJS_containerapp_deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: Azure/login@v1
      with:
       creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

    
    - uses: azure/docker-login@v1
      with:
        login-server: testregistry4572.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t testregistry4572.azurecr.io/reactsampleapp:${{ github.sha }}
        docker push testregistry4572.azurecr.io/reactsampleapp:${{ github.sha }} 
  deploy:
      runs-on: ubuntu-latest
      needs: build
      
      steps:
      - name: 'Login via Azure CLI'
        uses: Azure/login@v1
        with:
         creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
    
       
      - name: 'Deploy Container App'
        uses: Azure/cli@v1
        with:
         inlineScript: |
          echo "Installing containerapp extension"
          az extension add -n containerapp
          
          az containerapp create \
                --name testreactapp \
                --resource-group serviceprinciple \
                --environment managedEnvironment-serviceprincipl-9710 \
                --image testregistry4572.azurecr.io/reactsampleapp:${{ github.sha }} \
                --registry-server testregistry4572.azurecr.io \
                --registry-username ${{ secrets.REGISTRY_USERNAME }} \
                --registry-password ${{ secrets.REGISTRY_PASSWORD }}\
                --target-port 80 \
                --ingress 'external'
